apiVersion: v1
kind: pod 
metadata:
  name: sailorpod
spec:
  containers:
    - name: sailor 
      image: srikanthm46/sailor:1.0
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP